# Copyright (c) 2021-2025 Arm Limited.
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=6.0",
    "cmake<4.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
